### PR TITLE
Ticket 3: Refactor App architecture

### PR DESCRIPTION
**Pull request by BaoVu0712**
Ticket 3: Refactor App architecture #3 
### Description
- Create all package
image

### Include
- 3 main package: data, domain, ui

### CODE REVIEW

**Comment by PhunnMoc** [comment]
Can you add a package name: `mapper` inside `data` package?. Thanks

**Comment by BaoVu0712** [comment]
done

**Comment by BaoVu0712** [comment]
> Can you add a package name: `mapper` inside `data` package?. Thanks

@PhunnMoc

**Review by PhunnMoc — APPROVED** [review]
Lgtm

**Comment by HuynhKane** [comment]
> Can you add a package name: `mapper` inside `data` package?. Thanks
Yup

**Comment by HuynhKane** [comment]
> Can you add a package name: `mapper` inside `data` package?. Thanks

@PhunnMoc

**Pull request merged**
